### ISSUE TITLE
aniview alters background color?

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [jjcosgrove/jquery-aniview#15]
All I did was to add an "aniview" animation to two elements. It works partly as intended. The animation is fine and all that, but for some reason, it alters the background color of the element.

Notice how aniview alters the background color of the element, why does it do this? Is this a bug or did you purposely code aniview to behave like this? It doesn't make sense. 

Please, explain yourself. 

Notice only the first div child to ".bullet-points" has been given an aniview animation.

View gif: https://gyazo.com/5ae62ef17ce934a1febe74c4b0bc18e9

html
```
				div.bullet-points
					div
						h2.aniview.fast(data-av-animation="slideInUp") Stronger
						p.aniview.slow(data-av-animation="slideInUp") You will become stronger
					div
						h2 Faster
						p You will become faster
					div
						h2 Better
						p You will become better

```

**Comment by jjcosgrove** [comment]
Sorry for the delay, but will respond in case anyone else is interested...

I am not sure what markup you are using, but seems to be working fine?

https://jsfiddle.net/usn0bfhg/7/

If you can provide a demo/example of the issue on jsfiddle, I can take a look. Otherwise I will consider this issue closed.
