### ISSUE TITLE
Problem with seo (crawler)

### ISSUE THREAD

**Issue by uruk-hai-21** [jjcosgrove/jquery-aniview#17]
GoogleBot (crawler in general) doesn't like opacity setted to 0 and ignore it.
How is it possible to exclude aniview.js from the crawlers?

**Comment by uruk-hai-21** [comment]
This solution could be a good integration?

```
  var crawlerAgentRegex = (navigator.userAgent.match(/bot|google|aolbuild|baidu|bing|msn|duckduckgo|teoma|slurp|yandex/i)) ? ".no-aniew" : ".aniview";
  console.log(crawlerAgentRegex);
  
  var options = {
    animateThreshold: 100,
    scrollPollInterval: 20
  }
  jQuery(crawlerAgentRegex).AniView(options);
```

**Comment by jjcosgrove** [comment]
Hi @ajejebrazorf01 

Thanks for using AniView... since this is not really related to the plugin and it's operation I feel it best that and 'solution' remain implemented at the site level... your proposed solution seems painless enough for people to implement if so desired.

I shall close this issue for now.
